### ISSUE TITLE
Enable to define configs in deps.edn?

### ISSUE THREAD

**Issue by liquidz** [liquidz/build.edn#11]
e.g.
```clojure
{:build.edn/config {...}
 :paths []
 :deps {}}
```

**Comment by liquidz** [comment]
It is not good that the name is `deps`, but it contains other(build) information.

**Comment by NoahTheDuke** [comment]
I did this in [clein](https://github.com/NoahTheDuke/clein) and it works very nicely. Aliases can hold arbitrary data so if you have `{:aliases {... :build.edn/config {...}}}`, build.edn could use that as an alternative to a separate file.
