### ISSUE TITLE
Credential management

### ISSUE THREAD

**Issue by sunng87** [liquidz/build.edn#3]
The current implementation of `build.edn` relies on environment variables for clojars credentials. One thing I found pretty useful in lein is the gpg encrypted `credential.clj`, with which I can avoid to expose my password in plain text in environment variables. It would be nice to have similar support in `build.edn` to smooth deployment workflow at local.

**Comment by liquidz** [comment]
@sunng87 Thanks for your suggestion!
My main usage is to deploy from GitHub Actions, so I was expecting the password to be stored as secrets in GitHub.

But it is certainly bad to handle plain passwords when deploying from local, so I agree to be able to use GPG as same as leiningen :)

**Comment by sunng87** [comment]
Just realized the credential is set and used in upstream deps_deploy. I will create an issue there too.

**Comment by liquidz** [comment]
@sunng87 Just updated [dev](https://github.com/liquidz/build.edn/tree/dev) branch.
It is still a work in progress for now, but it should work.

In `dev` branch, `build.edn` file can have `deploy-repository` key.
https://github.com/liquidz/build.edn/blob/658cb384d30b1784fbdfce2bc7913afef681df2a/src/build_edn/schema.clj#L35-L40

e.g.
```clojure
{:deploy-repository {:id "clojars"}}
```
Default `:id` is `"clojars"`, so if you'd like to use clojars.org, the above settings is optional.

If `~/.m2/settings-security.xml` exists, build.edn will decrypt password by `deps-deploy.maven-settings`.
And if corresponding settings does not exists in `~/.m2/settings.xml`,  build.edn will refer environmental variables as before.

**Comment by sunng87** [comment]
@liquidz I confirm it works with maven encrypted password. Thank you for super fast response!

**Comment by liquidz** [comment]
@sunng87 Just released v0.3.82. Thank you so much!
https://github.com/liquidz/build.edn/releases/tag/0.3.82
