### ISSUE TITLE
Specify license in build.edn

### ISSUE THREAD

**Issue by sunng87** [liquidz/build.edn#31]
If I understand correctly there is no way at the moment to specify license information in build.edn, which will be in generated pom.

As clojars requires license in pom in 2024, it would be nice to be able to do that with build.edn

**Comment by liquidz** [comment]
@sunng87 Thanks for your notice. I missed it!
https://github.com/clojars/clojars-web/pull/874

I'll fix :)

**Comment by liquidz** [comment]
@sunng87 Sorry for late work.
I've added `licenses` option to `build.edn` file in `dev` branch.
* https://github.com/liquidz/build.edn/tree/dev#buildedn-file-format
* https://github.com/liquidz/build.edn/blob/dev/doc/format/licenses.adoc

Could you try `dev` branch?

**Comment by sunng87** [comment]
Just tried dev branch and I confirm it works.

**Comment by liquidz** [comment]
@sunng87 Thanks for your confirmation!
Just released v0.11.241 :)
